function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes
 
%  Auto-generated by MATLAB on 16-Jun-2009 23:03:52
 
%% Create legend
legend1 = legend(axes1,{'data1','data10','data11','data12','data13'});
 
